modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/yourusername/ascensionmod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

# Dependencies
[[dependencies.ascensionmod]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ascensionmod]]
modId="mysticalchemy"
mandatory=true
versionRange="0.0.6"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]] # Replace 'examplemod' with your mod's ID
modId="dimensionaldepths" # The mod ID of 'Dimensional Depths'
mandatory=true # Makes the dependency mandatory (your mod won't load without it)
versionRange="0.4.3" # Optional: Specify a version range (e.g., 1.0 or higher)
ordering="AFTER" # Load your mod after 'Dimensional Depths'
side="BOTH" # The dependency is required on both client and server