# General mod information
modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/YourUsername/YourMod/issues"

[[mods]]
modId="ascensionmod" # Updated to match your mod's ID
version="1.0.0"
displayName="Ascension Mod"
logoFile="ascensionmod_icon.png"
authors="YourUsername"
description='''
This mod adds new potions, origins, and teleportation mechanics to the game.
'''

# Dependencies
[[dependencies.ascensionmod]]
modId="forge"
mandatory=true
versionRange="[40.3.0,)" # Updated to match your Forge version
ordering="NONE"
side="BOTH"

[[dependencies.ascensionmod]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"

[[dependencies.ascensionmod]]
modId="origins"
mandatory=true
versionRange="[1.18.2-1.4.1,)" # Updated to match your Origins-Forge version
ordering="NONE"
side="BOTH"

[[dependencies.ascensionmod]]
modId="mysticalchemy"
mandatory=true
versionRange="[0.0.6,)" # Updated to allow newer versions
ordering="NONE"
side="BOTH"

[[dependencies.ascensionmod]]
modId="dimensionaldepths"
mandatory=true
versionRange="[0.4.3,)" # Updated to allow newer versions
ordering="AFTER"
side="BOTH"